import type { WorkflowContextPackSection, WorkflowContextPackSectionKey } from "@t3tools/contracts";

import { redactSensitiveText, truncateKeepingHead } from "./redactSensitiveText.ts";

/** Per-section body cap, applied to the exact persisted (post-redaction) text. */
export const CONTEXT_PACK_SECTION_MAX = 8_000;
/** Whole-pack cap across all section bodies. */
export const CONTEXT_PACK_TOTAL_MAX = 24_000;
/** Per-step cap inside `prior_outputs` before the section cap applies. */
export const CONTEXT_PACK_PER_STEP_MAX = 2_000;

/**
 * Shrink order when the pack exceeds {@link CONTEXT_PACK_TOTAL_MAX}. Diff stats are
 * the highest-value section for code-writing lanes, so they shrink last.
 */
const SHRINK_ORDER: ReadonlyArray<WorkflowContextPackSectionKey> = [
  "failed_attempts",
  "prior_outputs",
  "notes",
  "diff_summary",
];

/** A section shorter than this after truncation carries no signal — drop it whole. */
const MIN_USEFUL_SECTION = 64;

/**
 * Escape control characters so a crafted path, lane key, rename endpoint, or step
 * key cannot forge pack headings/rows once rendered into an agent prompt.
 */
export const escapeForPack = (value: string): string =>
  value.replace(/[\u0000-\u001f\u007f]/g, (ch) => {
    if (ch === "\n") return "\\n";
    if (ch === "\r") return "\\r";
    if (ch === "\t") return "\\t";
    return `\\x${ch.charCodeAt(0).toString(16).padStart(2, "0")}`;
  });

/** Redact first, then cap: redaction can expand short values (e.g. `KEY=x`). */
export const redactAndCap = (body: string, max = CONTEXT_PACK_SECTION_MAX): string =>
  truncateKeepingHead(redactSensitiveText(body), max);

/**
 * Apply the whole-pack cap. Sections are shortened (and dropped when nothing
 * useful survives) in {@link SHRINK_ORDER} until the total fits.
 */
export const applyTotalCap = (
  sections: ReadonlyArray<WorkflowContextPackSection>,
): ReadonlyArray<WorkflowContextPackSection> => {
  const working = sections.map((section) => ({ ...section }));
  const total = () => working.reduce((sum, section) => sum + section.body.length, 0);

  for (const key of SHRINK_ORDER) {
    if (total() <= CONTEXT_PACK_TOTAL_MAX) break;
    const index = working.findIndex((section) => section.key === key);
    if (index === -1) continue;
    const section = working[index];
    if (section === undefined) continue;
    const others = total() - section.body.length;
    const remaining = CONTEXT_PACK_TOTAL_MAX - others;
    if (remaining < MIN_USEFUL_SECTION) {
      working.splice(index, 1);
      continue;
    }
    section.body = truncateKeepingHead(section.body, remaining);
  }

  return working.filter((section) => section.body.length > 0);
};

/**
 * Canonicalize a submitted section set: trim bodies, drop blank/whitespace-only
 * sections (they would persist a zombie section that renders in the drawer and
 * injects nothing), and de-duplicate by key keeping the last occurrence.
 *
 * An empty result IS the deletion gesture, identical to an explicit `sections: []`.
 */
export const canonicalizeSubmittedSections = (
  sections: ReadonlyArray<{ readonly key: WorkflowContextPackSectionKey; readonly body: string }>,
): ReadonlyArray<{ readonly key: WorkflowContextPackSectionKey; readonly body: string }> => {
  const byKey = new Map<WorkflowContextPackSectionKey, string>();
  for (const section of sections) {
    const body = section.body.trim();
    if (body.length === 0) continue;
    byKey.set(section.key, body);
  }
  return Array.from(byKey, ([key, body]) => ({ key, body }));
};

/** Stable comparison for canonical no-op detection (order-insensitive). */
export const sectionsEqual = (
  a: ReadonlyArray<WorkflowContextPackSection>,
  b: ReadonlyArray<WorkflowContextPackSection>,
): boolean => {
  if (a.length !== b.length) return false;
  const key = (sections: ReadonlyArray<WorkflowContextPackSection>) =>
    [...sections]
      .sort((left, right) => left.key.localeCompare(right.key))
      .map((section) => `${section.key}\u0000${section.body}\u0000${String(section.autoGenerated)}`)
      .join("\u0001");
  return key(a) === key(b);
};

/**
 * Render a pack for prompt injection. Never passed through the template scanner —
 * the caller splices it over an opaque sentinel after all templating completes.
 */
export const renderContextPack = (input: {
  readonly fromLane: string;
  readonly sections: ReadonlyArray<WorkflowContextPackSection>;
}): string => {
  const heading = `## Handoff context from lane "${escapeForPack(input.fromLane)}"`;
  const body = input.sections.map((section) => `### ${section.key}\n${section.body}`).join("\n\n");
  return `${heading}\n\n${body}`;
};

export const CONTEXT_PACK_PLACEHOLDER = "{{ticket.contextPack}}";
export const CONTEXT_PACK_EMPTY = "(no handoff context)";

/** One file in a bounded ticket-diff stat. `added`/`deleted` are null for binaries. */
export interface ContextPackDiffFile {
  readonly path: string;
  readonly added: number | null;
  readonly deleted: number | null;
  readonly renamedFrom?: string;
}

/**
 * Parse `git diff --numstat -z` output.
 *
 * The `-z` records are `<added>TAB<deleted>TAB<path>NUL`, except renames, which
 * emit an EMPTY path field followed by two more NUL-terminated tokens (old, new).
 * Binaries report `-` for both counts.
 *
 * `truncated` must be the driver's own truncation flag: when the output was cut
 * mid-record the trailing bytes can still look like a well-formed record with a
 * short path, so everything after the last NUL is discarded before parsing
 * rather than trusted.
 */
export const parseNumstatZ = (
  stdout: string,
  truncated = false,
): { readonly files: ReadonlyArray<ContextPackDiffFile>; readonly partial: boolean } => {
  let text = stdout;
  let partial = truncated;
  if (truncated) {
    const lastNul = text.lastIndexOf("\u0000");
    text = lastNul < 0 ? "" : text.slice(0, lastNul + 1);
  }

  const tokens = text.split("\u0000");
  const files: Array<ContextPackDiffFile> = [];
  const count = (value: string): number | null => {
    if (value === "-") return null;
    const parsed = Number.parseInt(value, 10);
    return Number.isNaN(parsed) ? null : parsed;
  };

  let index = 0;
  while (index < tokens.length) {
    const token = tokens[index];
    if (token === undefined || token === "") {
      index += 1;
      continue;
    }
    const firstTab = token.indexOf("\t");
    const secondTab = firstTab < 0 ? -1 : token.indexOf("\t", firstTab + 1);
    if (firstTab < 0 || secondTab < 0) {
      // Not a record header — the output ended mid-field.
      partial = true;
      break;
    }
    const added = count(token.slice(0, firstTab));
    const deleted = count(token.slice(firstTab + 1, secondTab));
    const path = token.slice(secondTab + 1);
    if (path === "") {
      // Rename: the two following tokens are the old and new paths.
      const from = tokens[index + 1];
      const to = tokens[index + 2];
      if (from === undefined || to === undefined || to === "") {
        partial = true;
        break;
      }
      files.push({ path: to, added, deleted, renamedFrom: from });
      index += 3;
      continue;
    }
    files.push({ path, added, deleted });
    index += 1;
  }

  return { files, partial };
};

/**
 * Render the `diff_summary` body. Every path and rename endpoint is escaped: a
 * crafted filename would otherwise forge a pack heading once this lands in a
 * prompt. `partial` renders the count as "N+" so a truncated stat cannot read
 * as a complete one.
 */
export const renderDiffSummary = (input: {
  readonly files: ReadonlyArray<ContextPackDiffFile>;
  readonly partial: boolean;
}): string => {
  if (input.files.length === 0) {
    return "";
  }
  const header = `Ticket diff vs base: ${String(input.files.length)}${
    input.partial ? "+" : ""
  } files changed`;
  const lines = input.files.map((file) => {
    const name =
      file.renamedFrom === undefined
        ? escapeForPack(file.path)
        : `${escapeForPack(file.renamedFrom)} → ${escapeForPack(file.path)}`;
    if (file.added === null || file.deleted === null) {
      return `${name} (bin)`;
    }
    return `${name} (+${String(file.added)}/−${String(file.deleted)})`;
  });
  return [header, ...lines].join("\n");
};
