import type { WorkflowContextPackSection, WorkflowContextPackSectionKey } from "@t3tools/contracts";

import { redactSensitiveText, truncateKeepingHead } from "./redactSensitiveText.ts";

/** Per-section body cap, applied to the exact persisted (post-redaction) text. */
export const CONTEXT_PACK_SECTION_MAX = 8_000;
/** Whole-pack cap across all section bodies. */
export const CONTEXT_PACK_TOTAL_MAX = 24_000;
/** Per-step cap inside `prior_outputs` before the section cap applies. */
export const CONTEXT_PACK_PER_STEP_MAX = 2_000;

/**
 * Shrink order when the pack exceeds {@link CONTEXT_PACK_TOTAL_MAX}. Diff stats are
 * the highest-value section for code-writing lanes, so they shrink last.
 */
const SHRINK_ORDER: ReadonlyArray<WorkflowContextPackSectionKey> = [
  "failed_attempts",
  "prior_outputs",
  "notes",
  "diff_summary",
];

/** A section shorter than this after truncation carries no signal — drop it whole. */
const MIN_USEFUL_SECTION = 64;

/**
 * Escape control characters so a crafted path, lane key, rename endpoint, or step
 * key cannot forge pack headings/rows once rendered into an agent prompt.
 */
export const escapeForPack = (value: string): string =>
  // U+0085, U+2028 and U+2029 are line breaks to many renderers and tokenizers
  // even though they are not C0 controls, so a value carrying one could start a
  // new line with `##` and forge a heading. They escape like the C0 set.
  value.replace(/[\u0000-\u001f\u007f\u0085\u2028\u2029]/g, (ch) => {
    if (ch === "\n") return "\\n";
    if (ch === "\r") return "\\r";
    if (ch === "\t") return "\\t";
    return `\\x${ch.charCodeAt(0).toString(16).padStart(2, "0")}`;
  });

/** Redact first, then cap: redaction can expand short values (e.g. `KEY=x`). */
export const redactAndCap = (body: string, max = CONTEXT_PACK_SECTION_MAX): string =>
  truncateKeepingHead(redactSensitiveText(body), max);

/**
 * Apply the whole-pack cap. Sections are shortened (and dropped when nothing
 * useful survives) in {@link SHRINK_ORDER} until the total fits.
 */
export const applyTotalCap = (
  sections: ReadonlyArray<WorkflowContextPackSection>,
): ReadonlyArray<WorkflowContextPackSection> => {
  const working = sections.map((section) => ({ ...section }));
  const total = () => working.reduce((sum, section) => sum + section.body.length, 0);

  for (const key of SHRINK_ORDER) {
    if (total() <= CONTEXT_PACK_TOTAL_MAX) break;
    const index = working.findIndex((section) => section.key === key);
    if (index === -1) continue;
    const section = working[index];
    if (section === undefined) continue;
    const others = total() - section.body.length;
    const remaining = CONTEXT_PACK_TOTAL_MAX - others;
    if (remaining < MIN_USEFUL_SECTION) {
      working.splice(index, 1);
      continue;
    }
    section.body = truncateKeepingHead(section.body, remaining);
  }

  return working.filter((section) => section.body.length > 0);
};

/**
 * Canonicalize a submitted section set: trim bodies, drop blank/whitespace-only
 * sections (they would persist a zombie section that renders in the drawer and
 * injects nothing), and de-duplicate by key keeping the last occurrence.
 *
 * An empty result IS the deletion gesture, identical to an explicit `sections: []`.
 */
export const canonicalizeSubmittedSections = (
  sections: ReadonlyArray<{ readonly key: WorkflowContextPackSectionKey; readonly body: string }>,
): ReadonlyArray<{ readonly key: WorkflowContextPackSectionKey; readonly body: string }> => {
  const byKey = new Map<WorkflowContextPackSectionKey, string>();
  for (const section of sections) {
    const body = section.body.trim();
    if (body.length === 0) continue;
    byKey.set(section.key, body);
  }
  return Array.from(byKey, ([key, body]) => ({ key, body }));
};

/** Stable comparison for canonical no-op detection (order-insensitive). */
export const sectionsEqual = (
  a: ReadonlyArray<WorkflowContextPackSection>,
  b: ReadonlyArray<WorkflowContextPackSection>,
): boolean => {
  if (a.length !== b.length) return false;
  const key = (sections: ReadonlyArray<WorkflowContextPackSection>) =>
    [...sections]
      .sort((left, right) => left.key.localeCompare(right.key))
      .map((section) => `${section.key}\u0000${section.body}\u0000${String(section.autoGenerated)}`)
      .join("\u0001");
  return key(a) === key(b);
};

/**
 * Render a pack for prompt injection. Never passed through the template scanner —
 * the caller splices it over an opaque sentinel after all templating completes.
 */
/**
 * Neutralize heading syntax inside a section BODY.
 *
 * Bodies are the least trustworthy text in the pack: `prior_outputs` is verbatim
 * agent output and `failed_attempts` is verbatim error text, so either can carry
 * a line like `### notes` and manufacture a section the compiler never wrote —
 * one the destination agent cannot tell from a real one. Escaping only the
 * section key and the lane name would leave that wide open.
 *
 * A line-leading run of `#` is prefixed with a backslash, which still reads
 * plainly but can no longer open a heading.
 *
 * The split must cover EVERY character a consumer might treat as a line break,
 * not just `\n`: vertical tab and form feed are C0 controls, and U+0085/U+2028/
 * U+2029 are not controls at all, yet each starts a new line for some renderer
 * or tokenizer. Miss one and `text<break>### notes` forges a section while
 * reading as mid-line to this function.
 */
export const escapeBodyStructure = (body: string): string =>
  body
    .split(/(\r\n|\r|\n|\u000b|\u000c|\u0085|\u2028|\u2029)/)
    // Unicode CATEGORIES, not a hand-listed set: any leading run of whitespace,
    // control (Cc), format (Cf — soft hyphen, ZWSP/ZWJ, the bidi overrides,
    // U+FEFF) or non-spacing mark (Mn — variation selectors, the grapheme
    // joiner) is skipped before the `#` test. Enumerating these by hand loses:
    // every consumer that strips or ignores one more invisible character than
    // the list anticipates re-opens the hole, and the list is long enough that
    // omissions are not obvious on review.
    .map((part) => part.replace(/^([\s\p{Cc}\p{Cf}\p{Mn}]*)(#+)/u, "$1\\$2"))
    .join("");

export const renderContextPack = (input: {
  readonly fromLane: string;
  readonly sections: ReadonlyArray<WorkflowContextPackSection>;
}): string => {
  const heading = `## Handoff context from lane "${escapeForPack(input.fromLane)}"`;
  const body = input.sections
    .map((section) => `### ${section.key}\n${escapeBodyStructure(section.body)}`)
    .join("\n\n");
  return `${heading}\n\n${body}`;
};

export const CONTEXT_PACK_PLACEHOLDER = "{{ticket.contextPack}}";
export const CONTEXT_PACK_EMPTY = "(no handoff context)";

/** One file in a bounded ticket-diff stat. `added`/`deleted` are null for binaries. */
export interface ContextPackDiffFile {
  readonly path: string;
  readonly added: number | null;
  readonly deleted: number | null;
  readonly renamedFrom?: string;
}

/**
 * Parse `git diff --numstat -z` output.
 *
 * The `-z` records are `<added>TAB<deleted>TAB<path>NUL`, except renames, which
 * emit an EMPTY path field followed by two more NUL-terminated tokens (old, new).
 * Binaries report `-` for both counts.
 *
 * `truncated` must be the driver's own truncation flag: when the output was cut
 * mid-record the trailing bytes can still look like a well-formed record with a
 * short path, so everything after the last NUL is discarded before parsing
 * rather than trusted.
 */
export const parseNumstatZ = (
  stdout: string,
  truncated = false,
): { readonly files: ReadonlyArray<ContextPackDiffFile>; readonly partial: boolean } => {
  let text = stdout;
  let partial = truncated;
  if (truncated) {
    const lastNul = text.lastIndexOf("\u0000");
    text = lastNul < 0 ? "" : text.slice(0, lastNul + 1);
  }

  const tokens = text.split("\u0000");
  const files: Array<ContextPackDiffFile> = [];
  const count = (value: string): number | null => {
    if (value === "-") return null;
    const parsed = Number.parseInt(value, 10);
    return Number.isNaN(parsed) ? null : parsed;
  };

  let index = 0;
  while (index < tokens.length) {
    const token = tokens[index];
    if (token === undefined || token === "") {
      index += 1;
      continue;
    }
    const firstTab = token.indexOf("\t");
    const secondTab = firstTab < 0 ? -1 : token.indexOf("\t", firstTab + 1);
    if (firstTab < 0 || secondTab < 0) {
      // Not a record header — the output ended mid-field.
      partial = true;
      break;
    }
    const added = count(token.slice(0, firstTab));
    const deleted = count(token.slice(firstTab + 1, secondTab));
    const path = token.slice(secondTab + 1);
    if (path === "") {
      // Rename: the two following tokens are the old and new paths.
      const from = tokens[index + 1];
      const to = tokens[index + 2];
      if (from === undefined || to === undefined || to === "") {
        partial = true;
        break;
      }
      files.push({ path: to, added, deleted, renamedFrom: from });
      index += 3;
      continue;
    }
    files.push({ path, added, deleted });
    index += 1;
  }

  return { files, partial };
};

/**
 * Render the `diff_summary` body. Every path and rename endpoint is escaped: a
 * crafted filename would otherwise forge a pack heading once this lands in a
 * prompt. `partial` renders the count as "N+" so a truncated stat cannot read
 * as a complete one.
 */
export const renderDiffSummary = (input: {
  readonly files: ReadonlyArray<ContextPackDiffFile>;
  readonly partial: boolean;
}): string => {
  if (input.files.length === 0) {
    return "";
  }
  const header = `Ticket diff vs base: ${String(input.files.length)}${
    input.partial ? "+" : ""
  } files changed`;
  const lines = input.files.map((file) => {
    const name =
      file.renamedFrom === undefined
        ? escapeForPack(file.path)
        : `${escapeForPack(file.renamedFrom)} → ${escapeForPack(file.path)}`;
    if (file.added === null || file.deleted === null) {
      return `${name} (bin)`;
    }
    return `${name} (+${String(file.added)}/−${String(file.deleted)})`;
  });
  return [header, ...lines].join("\n");
};

/**
 * Build a per-render sentinel to stand in for the pack during templating.
 *
 * Two constraints:
 *  - It must never be LONGER than the placeholder it replaces. The description
 *    inline-or-spill decision is computed against the templated body, so a
 *    longer stand-in would push the description toward spilling before the pack
 *    text even exists.
 *  - It must not already occur in the text. A fixed sentinel that happened to
 *    appear inside a pack body, a ticket discussion, or a captured output would
 *    mis-splice, so the suffix varies per render and is collision-checked.
 */
export const makeContextPackSentinel = (haystack: string, seed: string): string => {
  // Derived from the step run id, not randomness: it only has to be unique
  // within THIS render, and a deterministic sentinel keeps the executor free of
  // ambient randomness (which this codebase routes through Effect) and makes the
  // splice reproducible in tests.
  const base = seed.replace(/[^A-Za-z0-9]/g, "").slice(-8);
  for (let attempt = 0; attempt < 8; attempt += 1) {
    const candidate = `«cp:${base}${attempt === 0 ? "" : String(attempt)}»`;
    if (candidate.length <= CONTEXT_PACK_PLACEHOLDER.length && !haystack.includes(candidate)) {
      return candidate;
    }
  }
  // Every short candidate collided. Widen without bound until one is unique:
  // returning an unchecked fallback would be the one case where the sentinel is
  // KNOWN to be collidable, which is exactly when a mis-splice happens. This
  // terminates because the haystack is finite and each candidate is longer than
  // the last. Correctness beats length neutrality here — extra characters only
  // nudge the description spill decision.
  for (let width = 1; ; width += 1) {
    const candidate = `«cp:${base}:${"x".repeat(width)}»`;
    if (!haystack.includes(candidate)) {
      return candidate;
    }
  }
};

/** Matches the placeholder anywhere, allowing internal whitespace. */
export const CONTEXT_PACK_PLACEHOLDER_PATTERN = /\{\{\s*ticket\.contextPack\s*\}\}/g;

/**
 * Replace the FIRST placeholder occurrence with `sentinel` and every later one
 * with the empty-pack text. The pack is single-use by design: splicing it twice
 * would double the prompt's largest block.
 */
export const substituteContextPackPlaceholder = (
  text: string,
  sentinel: string,
): { readonly text: string; readonly matched: number } => {
  let matched = 0;
  const next = text.replace(CONTEXT_PACK_PLACEHOLDER_PATTERN, () => {
    matched += 1;
    return matched === 1 ? sentinel : CONTEXT_PACK_EMPTY;
  });
  return { text: next, matched };
};
