import type { WorkflowContextPackSection, WorkflowContextPackSectionKey } from "@t3tools/contracts";

import { redactSensitiveText, truncateKeepingHead } from "./redactSensitiveText.ts";

/** Per-section body cap, applied to the exact persisted (post-redaction) text. */
export const CONTEXT_PACK_SECTION_MAX = 8_000;
/** Whole-pack cap across all section bodies. */
export const CONTEXT_PACK_TOTAL_MAX = 24_000;
/** Per-step cap inside `prior_outputs` before the section cap applies. */
export const CONTEXT_PACK_PER_STEP_MAX = 2_000;

/**
 * Shrink order when the pack exceeds {@link CONTEXT_PACK_TOTAL_MAX}. Diff stats are
 * the highest-value section for code-writing lanes, so they shrink last.
 */
const SHRINK_ORDER: ReadonlyArray<WorkflowContextPackSectionKey> = [
  "failed_attempts",
  "prior_outputs",
  "notes",
  "diff_summary",
];

/** A section shorter than this after truncation carries no signal — drop it whole. */
const MIN_USEFUL_SECTION = 64;

/**
 * Escape control characters so a crafted path, lane key, rename endpoint, or step
 * key cannot forge pack headings/rows once rendered into an agent prompt.
 */
export const escapeForPack = (value: string): string =>
  value.replace(/[\u0000-\u001f\u007f]/g, (ch) => {
    if (ch === "\n") return "\\n";
    if (ch === "\r") return "\\r";
    if (ch === "\t") return "\\t";
    return `\\x${ch.charCodeAt(0).toString(16).padStart(2, "0")}`;
  });

/** Redact first, then cap: redaction can expand short values (e.g. `KEY=x`). */
export const redactAndCap = (body: string, max = CONTEXT_PACK_SECTION_MAX): string =>
  truncateKeepingHead(redactSensitiveText(body), max);

/**
 * Apply the whole-pack cap. Sections are shortened (and dropped when nothing
 * useful survives) in {@link SHRINK_ORDER} until the total fits.
 */
export const applyTotalCap = (
  sections: ReadonlyArray<WorkflowContextPackSection>,
): ReadonlyArray<WorkflowContextPackSection> => {
  const working = sections.map((section) => ({ ...section }));
  const total = () => working.reduce((sum, section) => sum + section.body.length, 0);

  for (const key of SHRINK_ORDER) {
    if (total() <= CONTEXT_PACK_TOTAL_MAX) break;
    const index = working.findIndex((section) => section.key === key);
    if (index === -1) continue;
    const section = working[index];
    if (section === undefined) continue;
    const others = total() - section.body.length;
    const remaining = CONTEXT_PACK_TOTAL_MAX - others;
    if (remaining < MIN_USEFUL_SECTION) {
      working.splice(index, 1);
      continue;
    }
    section.body = truncateKeepingHead(section.body, remaining);
  }

  return working.filter((section) => section.body.length > 0);
};

/**
 * Canonicalize a submitted section set: trim bodies, drop blank/whitespace-only
 * sections (they would persist a zombie section that renders in the drawer and
 * injects nothing), and de-duplicate by key keeping the last occurrence.
 *
 * An empty result IS the deletion gesture, identical to an explicit `sections: []`.
 */
export const canonicalizeSubmittedSections = (
  sections: ReadonlyArray<{ readonly key: WorkflowContextPackSectionKey; readonly body: string }>,
): ReadonlyArray<{ readonly key: WorkflowContextPackSectionKey; readonly body: string }> => {
  const byKey = new Map<WorkflowContextPackSectionKey, string>();
  for (const section of sections) {
    const body = section.body.trim();
    if (body.length === 0) continue;
    byKey.set(section.key, body);
  }
  return Array.from(byKey, ([key, body]) => ({ key, body }));
};

/** Stable comparison for canonical no-op detection (order-insensitive). */
export const sectionsEqual = (
  a: ReadonlyArray<WorkflowContextPackSection>,
  b: ReadonlyArray<WorkflowContextPackSection>,
): boolean => {
  if (a.length !== b.length) return false;
  const key = (sections: ReadonlyArray<WorkflowContextPackSection>) =>
    [...sections]
      .sort((left, right) => left.key.localeCompare(right.key))
      .map((section) => `${section.key}\u0000${section.body}\u0000${String(section.autoGenerated)}`)
      .join("\u0001");
  return key(a) === key(b);
};

/**
 * Render a pack for prompt injection. Never passed through the template scanner —
 * the caller splices it over an opaque sentinel after all templating completes.
 */
export const renderContextPack = (input: {
  readonly fromLane: string;
  readonly sections: ReadonlyArray<WorkflowContextPackSection>;
}): string => {
  const heading = `## Handoff context from lane "${escapeForPack(input.fromLane)}"`;
  const body = input.sections
    .map((section) => `### ${section.key}\n${section.body}`)
    .join("\n\n");
  return `${heading}\n\n${body}`;
};

export const CONTEXT_PACK_PLACEHOLDER = "{{ticket.contextPack}}";
export const CONTEXT_PACK_EMPTY = "(no handoff context)";
