// @effect-diagnostics globalTimers:off
import { assert, it } from "@effect/vitest";
import * as Effect from "effect/Effect";
import * as Layer from "effect/Layer";
import * as Stream from "effect/Stream";
import * as SqlClient from "effect/unstable/sql/SqlClient";

import { MigrationsLive } from "../../persistence/Migrations.ts";
import { SqlitePersistenceMemory } from "../../persistence/Layers/Sqlite.ts";
import { BoardRegistry } from "../Services/BoardRegistry.ts";
import { ScriptCancelRegistry } from "../Services/ScriptCancelRegistry.ts";
import { StepExecutor, type StepExecutorShape } from "../Services/StepExecutor.ts";
import { WorkflowEngine } from "../Services/WorkflowEngine.ts";
import { WorkflowEventStore } from "../Services/WorkflowEventStore.ts";
import { WorkflowReadModel } from "../Services/WorkflowReadModel.ts";
import { WorkflowFoundationLive } from "../WorkflowFoundationLive.ts";
import { ApprovalGateLive } from "./ApprovalGate.ts";
import { BoardRegistryLive } from "./BoardRegistry.ts";
import { PredicateEvaluatorLive } from "./PredicateEvaluator.ts";
import { WorkflowBoardSaveLocksLive } from "./WorkflowBoardSaveLocks.ts";
import { WorkflowEventCommitterLive } from "./WorkflowEventCommitter.ts";
import { WorkflowEngineLayer } from "./WorkflowEngine.ts";
import { DeterministicWorkflowIds } from "./WorkflowIds.ts";
import { WorkflowRoutingContextBuilderLive } from "./WorkflowRoutingContextBuilder.ts";

const succeedingExecutor = Layer.succeed(StepExecutor, {
  execute: () => Effect.succeed({ _tag: "completed" as const }),
} satisfies StepExecutorShape);

const layer = it.layer(
  WorkflowEngineLayer.pipe(
    Layer.provideMerge(WorkflowEventCommitterLive),
    Layer.provideMerge(
      Layer.succeed(ScriptCancelRegistry, {
        register: () => Effect.void,
        unregister: () => Effect.void,
        cancel: () => Effect.void,
      }),
    ),
    Layer.provideMerge(succeedingExecutor),
    Layer.provideMerge(ApprovalGateLive),
    Layer.provideMerge(BoardRegistryLive),
    Layer.provideMerge(PredicateEvaluatorLive),
    Layer.provideMerge(WorkflowRoutingContextBuilderLive),
    Layer.provideMerge(WorkflowBoardSaveLocksLive),
    Layer.provideMerge(DeterministicWorkflowIds),
    Layer.provideMerge(WorkflowFoundationLive),
    Layer.provideMerge(MigrationsLive),
    Layer.provideMerge(SqlitePersistenceMemory),
  ),
);

// Two manual lanes: the ticket parks in `review` with no pipeline to run, which
// is the state a real handoff pack is edited in.
const definition = {
  name: "packs",
  lanes: [
    { key: "review", name: "Review", entry: "manual" },
    { key: "elsewhere", name: "Elsewhere", entry: "manual" },
  ],
};

/**
 * Seed a compiled pack directly. The compiler that emits
 * `TicketContextPackCompiled` lands in a later task; the edit path it feeds is
 * already reachable and is what these tests cover.
 */
const seedPack = (
  ticketId: string,
  forLane: string,
  sections: ReadonlyArray<{ key: string; body: string; autoGenerated: boolean }>,
) =>
  Effect.gen(function* () {
    const sql = yield* SqlClient.SqlClient;
    yield* sql`
      INSERT INTO projection_context_pack (
        ticket_id, for_lane, from_lane, compiled_at, edited_at, sections_json
      )
      VALUES (
        ${ticketId}, ${forLane}, 'implement', '2026-07-25T00:00:00.000Z', NULL,
        ${JSON.stringify(sections)}
      )
      ON CONFLICT (ticket_id, for_lane) DO UPDATE SET
        sections_json = excluded.sections_json, edited_at = NULL
    `;
  });

const newTicket = (boardId: string, title: string) =>
  Effect.gen(function* () {
    const registry = yield* BoardRegistry;
    yield* registry.register(boardId as never, definition);
    const engine = yield* WorkflowEngine;
    return yield* engine.createTicket({
      boardId: boardId as never,
      title,
      initialLane: "review" as never,
    });
  });

const editedEventCount = (ticketId: string) =>
  Effect.gen(function* () {
    const store = yield* WorkflowEventStore;
    const events = yield* Stream.runCollect(store.readByTicket(ticketId as never)).pipe(
      Effect.map((chunk) => Array.from(chunk)),
    );
    return events.filter((event) => event.type === "TicketContextPackEdited").length;
  });

layer("WorkflowEngine context packs", (it) => {
  it.effect("rejects an edit when no pack was compiled for the lane", () =>
    Effect.gen(function* () {
      const engine = yield* WorkflowEngine;
      const ticket = yield* newTicket("b-pack-none", "No pack");

      const failure = yield* engine
        .editTicketContextPack({
          ticketId: ticket,
          forLane: "review" as never,
          sections: [{ key: "notes" as never, body: "hi" }],
        })
        .pipe(Effect.flip);
      assert.include(failure.message, "no context pack for this lane");
    }),
  );

  it.effect("rejects an edit aimed at a lane the ticket is not in", () =>
    Effect.gen(function* () {
      const engine = yield* WorkflowEngine;
      const ticket = yield* newTicket("b-pack-lane", "Wrong lane");
      yield* seedPack(ticket, "elsewhere", [{ key: "notes", body: "stale", autoGenerated: true }]);

      const failure = yield* engine
        .editTicketContextPack({
          ticketId: ticket,
          forLane: "elsewhere" as never,
          sections: [{ key: "notes" as never, body: "hi" }],
        })
        .pipe(Effect.flip);
      assert.include(failure.message, "current lane");
    }),
  );

  it.effect("persists an edited section, redacts it, and flips autoGenerated", () =>
    Effect.gen(function* () {
      const engine = yield* WorkflowEngine;
      const read = yield* WorkflowReadModel;
      const ticket = yield* newTicket("b-pack-edit", "Edit");
      yield* seedPack(ticket, "review", [
        { key: "notes", body: "compiled note", autoGenerated: true },
        { key: "diff_summary", body: "3 files changed", autoGenerated: true },
      ]);

      const result = yield* engine.editTicketContextPack({
        ticketId: ticket,
        forLane: "review" as never,
        sections: [
          // Trailing whitespace is canonicalized away.
          { key: "notes" as never, body: "  human note  " },
          // Resubmitted byte-identical: keeps its auto-generated flag.
          { key: "diff_summary" as never, body: "3 files changed" },
        ],
      });

      const notes = result.sections.find((section) => section.key === "notes");
      assert.equal(notes?.body, "human note");
      assert.isFalse(notes?.autoGenerated);
      const diff = result.sections.find((section) => section.key === "diff_summary");
      assert.isTrue(diff?.autoGenerated);

      const stored = yield* read.getContextPack(ticket, "review" as never);
      assert.deepStrictEqual(stored?.sections, result.sections);
      assert.isDefined(stored?.editedAt);
    }),
  );

  it.effect("redacts secrets out of a submitted body", () =>
    Effect.gen(function* () {
      const engine = yield* WorkflowEngine;
      const ticket = yield* newTicket("b-pack-redact", "Redact");
      yield* seedPack(ticket, "review", [{ key: "notes", body: "x", autoGenerated: true }]);

      const result = yield* engine.editTicketContextPack({
        ticketId: ticket,
        forLane: "review" as never,
        sections: [
          {
            key: "notes" as never,
            body: "use AWS_SECRET_ACCESS_KEY=abcdefghijklmnopqrstuvwxyz0123456789ABCD",
          },
        ],
      });
      assert.notInclude(result.sections[0]?.body ?? "", "abcdefghijklmnopqrstuvwxyz0123456789ABCD");
    }),
  );

  it.effect("treats a byte-identical resubmission as a no-op that never stamps editedAt", () =>
    Effect.gen(function* () {
      const engine = yield* WorkflowEngine;
      const read = yield* WorkflowReadModel;
      const ticket = yield* newTicket("b-pack-noop", "No-op");
      yield* seedPack(ticket, "review", [{ key: "notes", body: "unchanged", autoGenerated: true }]);

      const result = yield* engine.editTicketContextPack({
        ticketId: ticket,
        forLane: "review" as never,
        // Same content, only reordered/padded — canonicalization makes it identical.
        sections: [{ key: "notes" as never, body: "unchanged " }],
      });
      assert.deepStrictEqual(result.sections, [
        { key: "notes", body: "unchanged", autoGenerated: true },
      ]);

      const stored = yield* read.getContextPack(ticket, "review" as never);
      assert.equal(stored?.editedAt, undefined);
      assert.equal(yield* editedEventCount(ticket), 0);
    }),
  );

  it.effect("deletes the pack when every submitted section is blank", () =>
    Effect.gen(function* () {
      const engine = yield* WorkflowEngine;
      const read = yield* WorkflowReadModel;
      const ticket = yield* newTicket("b-pack-delete", "Delete");
      yield* seedPack(ticket, "review", [{ key: "notes", body: "goes away", autoGenerated: true }]);

      const result = yield* engine.editTicketContextPack({
        ticketId: ticket,
        forLane: "review" as never,
        sections: [{ key: "notes" as never, body: "   \n\t " }],
      });
      assert.deepStrictEqual(result.sections, []);

      const stored = yield* read.getContextPack(ticket, "review" as never);
      assert.isNull(stored);
      assert.equal(yield* editedEventCount(ticket), 1);
    }),
  );
});
