import type {
  BoardId,
  LaneKey,
  MessageId,
  StepRunId,
  ThreadId,
  TicketAttachment,
  TicketId,
  TurnId,
  WorkflowEventId,
  WorkflowParkActionResult,
  WorkflowStepUsage,
  WorkflowContextPackSection,
} from "@t3tools/contracts";
import * as Context from "effect/Context";
import type * as Effect from "effect/Effect";

import type { WorkflowEventStoreError } from "./Errors.ts";

export type RecoveredStepResult =
  | { readonly _tag: "completed"; readonly output?: unknown; readonly usage?: WorkflowStepUsage }
  | {
      readonly _tag: "failed";
      readonly error: string;
      readonly retryable?: boolean;
      readonly usage?: WorkflowStepUsage;
      readonly failureClass?: import("@t3tools/contracts").WorkflowFailureClass;
    }
  | { readonly _tag: "blocked"; readonly reason: string };

export interface WorkflowEngineShape {
  readonly createTicket: (input: {
    readonly boardId: BoardId;
    readonly title: string;
    readonly description?: string;
    readonly initialLane: LaneKey;
    readonly dependsOn?: ReadonlyArray<TicketId>;
    readonly tokenBudget?: number;
  }) => Effect.Effect<TicketId, WorkflowEventStoreError>;
  readonly editTicket: (input: {
    readonly ticketId: TicketId;
    readonly title?: string | undefined;
    readonly description?: string | undefined;
    readonly dependsOn?: ReadonlyArray<TicketId> | undefined;
    readonly tokenBudget?: number | null | undefined;
  }) => Effect.Effect<void, WorkflowEventStoreError>;
  /**
   * Full-set pack edit. Owns commit-time revalidation (lane still current, pack
   * still present) under the admission lock, redact-then-cap, canonical no-op
   * detection, and per-section `autoGenerated` diffing. Returns the PERSISTED
   * post-redaction sections so the drawer can show what will actually be injected.
   */
  readonly editTicketContextPack: (input: {
    readonly ticketId: TicketId;
    readonly forLane: LaneKey;
    readonly sections: ReadonlyArray<{ readonly key: string; readonly body: string }>;
  }) => Effect.Effect<
    { readonly sections: ReadonlyArray<WorkflowContextPackSection> },
    WorkflowEventStoreError
  >;
  readonly moveTicket: (
    ticketId: TicketId,
    toLane: LaneKey,
  ) => Effect.Effect<void, WorkflowEventStoreError>;
  /**
   * SLA sweeper op: breach (+ optional escalation move/queue) under admission
   * OUTER → save INNER. Never re-enters public moveTicket. Returns:
   * escalated | queued | notified | stale.
   */
  readonly escalateTicketSla: (input: {
    readonly ticketId: TicketId;
    readonly expectedLaneKey: LaneKey;
    readonly expectedEntryToken: string;
    readonly nowMs?: Effect.Effect<number>;
  }) => Effect.Effect<"escalated" | "queued" | "notified" | "stale", WorkflowEventStoreError>;
  // Unpark: re-resolve the parked ticket's actions from the CURRENT board
  // definition (by `park_origin` fingerprint, never a snapshot), then perform a
  // manual `TicketMovedToLane` into the chosen action's target lane. The
  // authoritative parked-state compare-and-act on `parkedEventId` runs INSIDE
  // the admission lock: a ticket that is no longer parked, or whose parked event
  // id no longer matches, yields `"stale"` without moving. Fails with a typed
  // error when the actions can no longer be resolved (definition edited/reverted)
  // or the action's target lane no longer exists.
  readonly invokeParkAction: (
    ticketId: TicketId,
    actionIndex: number,
    parkedEventId: WorkflowEventId,
  ) => Effect.Effect<WorkflowParkActionResult, WorkflowEventStoreError>;
  // Committer-facing UNLOCKED ops for the work-source syncer (Task 9). The CALLER
  // MUST already hold the board save lock for the affected board AND be inside an
  // open `sql.withTransaction`; these never acquire the save lock, never open a
  // transaction, and never take the admission lock. Driving them is how a batch
  // syncer creates/closes/edits tickets under ONE lock + ONE transaction per
  // chunk without deadlocking the non-reentrant save lock.
  readonly createTicketAndEnterUnlocked: (input: {
    readonly boardId: BoardId;
    readonly title: string;
    readonly description?: string;
    readonly destinationLane: LaneKey;
  }) => Effect.Effect<
    { readonly ticketId: TicketId; readonly outcome: "moved" | "queued" | "none" },
    WorkflowEventStoreError
  >;
  readonly closeTicketFromSourceUnlocked: (
    ticketId: TicketId,
    closedLane: LaneKey,
  ) => Effect.Effect<void, WorkflowEventStoreError>;
  // Inverse of closeTicketFromSourceUnlocked: route a source-closed ticket OUT of
  // its current (closed) lane back into `destinationLane` when the upstream item
  // is reopened. DB-only move via the external path (no provider IO in-tx). Like
  // the close, any auto-lane pipeline start is dropped here (single-transaction
  // reason) and the committer's post-commit recoverBoardWip sweep starts it.
  readonly reopenTicketFromSourceUnlocked: (
    ticketId: TicketId,
    destinationLane: LaneKey,
  ) => Effect.Effect<void, WorkflowEventStoreError>;
  // Snapshot the ticket's cancellable provider turns (pending/started dispatch
  // outbox rows). The source committer captures this INSIDE the chunk tx, BEFORE
  // closeTicketFromSourceUnlocked tombstones those rows, then replays it through
  // supersedeProviderWorkForTicket AFTER the tx commits.
  readonly cancellableProviderTurnsForTicket: (
    ticketId: TicketId,
  ) => Effect.Effect<
    ReadonlyArray<{ readonly threadId: ThreadId; readonly turnId: TurnId | null }>,
    WorkflowEventStoreError
  >;
  // POST-TX provider cancellation for a source-closed ticket: interrupt the
  // running pipeline fiber + cancel the captured provider turns. NO DB writes
  // (the in-tx close already tombstoned the outbox). Idempotent. The committer
  // calls this after the chunk transaction commits so no provider/fiber IO runs
  // inside the transaction.
  readonly supersedeProviderWorkForTicket: (
    ticketId: TicketId,
    turns: ReadonlyArray<{ readonly threadId: ThreadId; readonly turnId: TurnId | null }>,
  ) => Effect.Effect<void, WorkflowEventStoreError>;
  // Snapshot the ticket's stored per-agent session thread ids. The source
  // committer captures this INSIDE the chunk tx, BEFORE closeTicketFromSourceUnlocked
  // tears down (deletes) the rows on its terminal entry, then replays it through
  // stopAgentSessionsForTicket AFTER the tx commits. `provider.stopSession` is a
  // non-rollbackable live side effect (it kills the provider session + does its
  // own SQL write) so it must never run inside the chunk transaction.
  readonly terminalAgentSessionThreadsForTicket: (
    ticketId: TicketId,
  ) => Effect.Effect<ReadonlyArray<string>, WorkflowEventStoreError>;
  // POST-TX best-effort live stop of the agent-session threads snapshotted by
  // terminalAgentSessionThreadsForTicket. The in-tx teardown already deleted the
  // rows; this only fires provider.stopSession after the chunk transaction commits.
  readonly stopAgentSessionsForTicket: (
    threadIds: ReadonlyArray<string>,
  ) => Effect.Effect<void, WorkflowEventStoreError>;
  readonly editTicketFieldsUnlocked: (
    ticketId: TicketId,
    fields: { readonly title?: string | undefined; readonly description?: string | undefined },
  ) => Effect.Effect<void, WorkflowEventStoreError>;
  // Acquire the per-board admission semaphore (the WIP read-decide serializer).
  // The source committer MUST wrap its chunk in this (OUTER) -> the board save
  // lock (INNER) -> the transaction, matching the public enterLane lock order
  // (admission->save), so sync admits serialize against concurrent user moves
  // and cannot violate a WIP limit. The unlocked enterLane cores assume this is
  // already held.
  readonly withBoardAdmissionLock: <A, E, R>(
    boardId: BoardId,
    effect: Effect.Effect<A, E, R>,
  ) => Effect.Effect<A, E, R>;
  readonly runLane: (ticketId: TicketId) => Effect.Effect<void, WorkflowEventStoreError>;
  // Webhook-correlated event: evaluates the ticket's current lane onEvent
  // matchers and moves/queues the ticket like a manual move when one fires.
  // "parked" is distinct from "noop": the event matched and durably parked the
  // ticket (a real, recorded outcome), whereas "noop" means no matcher fired
  // at all. "skipped_parked" means the ticket was already parked and the event
  // was recorded as history-only (never evaluated) — see the parked-ticket
  // short-circuit in ingestExternalEvent.
  readonly ingestExternalEvent: (input: {
    readonly boardId: BoardId;
    readonly name: string;
    readonly ticketId: TicketId;
    readonly payload: unknown;
  }) => Effect.Effect<
    {
      readonly outcome: "moved" | "queued" | "noop" | "parked" | "skipped_parked";
      readonly toLane?: string;
    },
    WorkflowEventStoreError
  >;
  readonly resolveApproval: (
    stepRunId: StepRunId,
    approved: boolean,
  ) => Effect.Effect<void, WorkflowEventStoreError>;
  readonly answerTicketStep: (input: {
    readonly stepRunId: StepRunId;
    readonly text?: string | undefined;
    readonly attachments?: ReadonlyArray<TicketAttachment> | undefined;
  }) => Effect.Effect<void, WorkflowEventStoreError>;
  /**
   * Mid-run guidance into a live agent step. Returns `{ accepted: true }` on
   * reserve+submit (and on idempotent retries). Failures are typed store errors
   * whose message is a frozen STEER_REJECTION constant.
   */
  readonly steerTicketStep: (input: {
    readonly ticketId: TicketId;
    readonly stepRunId: StepRunId;
    readonly messageId: MessageId;
    readonly text: string;
  }) => Effect.Effect<{ readonly accepted: true }, WorkflowEventStoreError>;
  readonly postTicketMessage: (input: {
    readonly ticketId: TicketId;
    readonly text?: string | undefined;
    readonly attachments?: ReadonlyArray<TicketAttachment> | undefined;
  }) => Effect.Effect<void, WorkflowEventStoreError>;
  readonly editTicketMessage: (input: {
    readonly ticketId: TicketId;
    readonly messageId: MessageId;
    readonly body: string;
  }) => Effect.Effect<void, WorkflowEventStoreError>;
  readonly cancelStep: (stepRunId: StepRunId) => Effect.Effect<void, WorkflowEventStoreError>;
  readonly cancelBoardPipelines: (boardId: BoardId) => Effect.Effect<void, WorkflowEventStoreError>;
  readonly cancelTicketPipelines: (
    ticketId: TicketId,
  ) => Effect.Effect<void, WorkflowEventStoreError>;
  readonly recoverBoardWip: (boardId: BoardId) => Effect.Effect<void, WorkflowEventStoreError>;
  readonly completeRecoveredStep: (
    stepRunId: StepRunId,
    result: RecoveredStepResult,
    captureTurn?: { readonly threadId: ThreadId; readonly turnId: TurnId },
  ) => Effect.Effect<void, WorkflowEventStoreError>;
}

export class WorkflowEngine extends Context.Service<WorkflowEngine, WorkflowEngineShape>()(
  "t3/workflow/Services/WorkflowEngine",
) {}
